import { useEffect, useState } from "react";
import CowSelector from "../components/CowSelector";
import { createMilk, getCows, getMilk } from "../services/api";

const empty = { cow_id: "", date: new Date().toISOString().slice(0,10), morning_milk: "", evening_milk: "", notes: "" };
export default function Milk() {
  const [form, setForm] = useState(empty); const [records, setRecords] = useState([]); const [filter, setFilter] = useState(""); const [cows, setCows] = useState([]); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load(cowId=filter){ try { setRecords(await getMilk(cowId || undefined)); } catch(e){ setError(e?.response?.data?.detail || "Could not load milk records."); } }
  useEffect(()=>{ getCows().then(setCows).catch(()=>{}); load(); },[]);
  async function submit(e){ e.preventDefault(); setError(""); setMessage(""); try { await createMilk({...form, morning_milk:Number(form.morning_milk), evening_milk:Number(form.evening_milk)}); setMessage("Milk record saved. Total milk was calculated automatically."); setForm({...empty, cow_id:form.cow_id}); await load(filter); } catch(e){ setError(e?.response?.data?.detail || "Could not save milk record."); } }
  const cowName=(id)=>{const c=cows.find(x=>x.id===id); return c?`${c.cow_id} — ${c.name}`:id};
  return <div className="mx-auto max-w-7xl space-y-6"><div><h1 className="text-3xl font-bold text-slate-900">Milk Records</h1><p className="mt-2 text-slate-500">Record morning/evening production. Total milk is calculated by the backend.</p></div>{error&&<div className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}{message&&<div className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{message}</div>}
  <form onSubmit={submit} className="rounded-2xl border bg-white p-6 shadow-sm"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><CowSelector value={form.cow_id} onChange={(v)=>setForm({...form,cow_id:v})}/><label className="block"><span className="text-sm font-medium">Date</span><input type="date" required value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="mt-1 w-full rounded-xl border px-4 py-3"/></label><label className="block"><span className="text-sm font-medium">Morning milk (L)</span><input type="number" min="0" step="0.01" required value={form.morning_milk} onChange={e=>setForm({...form,morning_milk:e.target.value})} className="mt-1 w-full rounded-xl border px-4 py-3"/></label><label className="block"><span className="text-sm font-medium">Evening milk (L)</span><input type="number" min="0" step="0.01" required value={form.evening_milk} onChange={e=>setForm({...form,evening_milk:e.target.value})} className="mt-1 w-full rounded-xl border px-4 py-3"/></label><label className="block md:col-span-2"><span className="text-sm font-medium">Notes</span><input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="mt-1 w-full rounded-xl border px-4 py-3"/></label></div><button className="mt-5 rounded-xl bg-emerald-600 px-5 py-3 font-semibold text-white">Save Milk Record</button></form>
  <div className="rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-5 md:flex-row md:items-center md:justify-between"><h2 className="font-semibold">Saved records</h2><select value={filter} onChange={e=>{setFilter(e.target.value);load(e.target.value)}} className="rounded-xl border bg-white px-4 py-2"><option value="">All cows</option>{cows.map(c=><option key={c.id} value={c.id}>{c.cow_id} — {c.name}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50"><tr>{["Date","Cow","Morning","Evening","Total","Notes"].map(h=><th key={h} className="px-4 py-3 font-medium text-slate-500">{h}</th>)}</tr></thead><tbody className="divide-y">{records.map(r=><tr key={r.id}><td className="px-4 py-3">{r.date}</td><td className="px-4 py-3">{cowName(r.cow_id)}</td><td className="px-4 py-3">{r.morning_milk} L</td><td className="px-4 py-3">{r.evening_milk} L</td><td className="px-4 py-3 font-semibold">{r.total_milk} L</td><td className="px-4 py-3">{r.notes||"—"}</td></tr>)}</tbody></table></div>{records.length===0&&<p className="p-6 text-sm text-slate-400">No milk records found.</p>}</div></div>;
}
